#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("EricIntrusionApp.Resource", IsApplication=true)]

namespace EricIntrusionApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::SQLite.Resource.String.ApplicationName = global::EricIntrusionApp.Resource.String.ApplicationName;
			global::SQLite.Resource.String.Hello = global::EricIntrusionApp.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int AppLogo2 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ButtonBehaviour = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int configurationsettings = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int HistoryIcon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int home = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Icon = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int @lock = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int next2 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ProtectionIcon = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int SettingsIcon = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int User2 = 2130837514;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060022
			public const int EmailText = 2131099682;
			
			// aapt resource value: 0x7f060011
			public const int IntruderPictureView = 2131099665;
			
			// aapt resource value: 0x7f060021
			public const int NameText = 2131099681;
			
			// aapt resource value: 0x7f060023
			public const int PasswordText = 2131099683;
			
			// aapt resource value: 0x7f060012
			public const int PictureScreenTextView = 2131099666;
			
			// aapt resource value: 0x7f060017
			public const int ScrollView1 = 2131099671;
			
			// aapt resource value: 0x7f060009
			public const int UnnlockImageView = 2131099657;
			
			// aapt resource value: 0x7f060016
			public const int checkBox = 2131099670;
			
			// aapt resource value: 0x7f060004
			public const int dateTextView = 2131099652;
			
			// aapt resource value: 0x7f06001b
			public const int emailEditText = 2131099675;
			
			// aapt resource value: 0x7f06000f
			public const int historyImageButton = 2131099663;
			
			// aapt resource value: 0x7f060000
			public const int historyListView = 2131099648;
			
			// aapt resource value: 0x7f060006
			public const int imageView1 = 2131099654;
			
			// aapt resource value: 0x7f060002
			public const int intruderImageView = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int linearLayout1 = 2131099649;
			
			// aapt resource value: 0x7f060018
			public const int linearLayout12 = 2131099672;
			
			// aapt resource value: 0x7f060003
			public const int linearLayout2 = 2131099651;
			
			// aapt resource value: 0x7f060010
			public const int lockImageButton = 2131099664;
			
			// aapt resource value: 0x7f06001a
			public const int nameEditText = 2131099674;
			
			// aapt resource value: 0x7f06001d
			public const int passwordEditText = 2131099677;
			
			// aapt resource value: 0x7f06001c
			public const int remailEditText = 2131099676;
			
			// aapt resource value: 0x7f060005
			public const int reportTextView = 2131099653;
			
			// aapt resource value: 0x7f06001e
			public const int rpasswordEditText = 2131099678;
			
			// aapt resource value: 0x7f06001f
			public const int saveDetailsButton = 2131099679;
			
			// aapt resource value: 0x7f060015
			public const int settingDescriptionTextView = 2131099669;
			
			// aapt resource value: 0x7f060014
			public const int settingNameTextView = 2131099668;
			
			// aapt resource value: 0x7f06000d
			public const int settingsImageButton = 2131099661;
			
			// aapt resource value: 0x7f060013
			public const int settingslistView = 2131099667;
			
			// aapt resource value: 0x7f06000a
			public const int tableLayout1 = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int tableRow3 = 2131099659;
			
			// aapt resource value: 0x7f06000e
			public const int tableRow4 = 2131099662;
			
			// aapt resource value: 0x7f060007
			public const int textView1 = 2131099655;
			
			// aapt resource value: 0x7f060019
			public const int textView2 = 2131099673;
			
			// aapt resource value: 0x7f060020
			public const int textView4 = 2131099680;
			
			// aapt resource value: 0x7f060008
			public const int unlockTextView = 2131099656;
			
			// aapt resource value: 0x7f060024
			public const int updateAccountDetails = 2131099684;
			
			// aapt resource value: 0x7f06000c
			public const int userImageButton = 2131099660;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int History = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int HistoryLayout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int LockScreen = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int PictureScreen = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Settings = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Settingslayout = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int SetupOne = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int SetupTwo = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int StartupActivity = 2130903049;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int siren = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int siren1 = 2130968577;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050006
			public const int Account = 2131034118;
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f050007
			public const int History = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int Lock = 2131034120;
			
			// aapt resource value: 0x7f050005
			public const int OptionSpinner = 2131034117;
			
			// aapt resource value: 0x7f050009
			public const int Settings = 2131034121;
			
			// aapt resource value: 0x7f050004
			public const int ViewOptions = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int app_name = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int hello = 2131034114;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
